# Generated by Django 5.2.17 on 2026-09-22 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, choices=[('usps', 'USPS'), ('ups', 'UPS'), ('fedex', 'FedEx'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_other',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('unfulfilled', 'Waiting for payment'), ('needs_packing', 'Needs packing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('completed', 'Completed')], db_index=True, default='unfulfilled', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='packed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderaudit',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('customer_confirmation', 'Customer order confirmation'), ('owner_new_order', 'Owner new-order notice'), ('shipping_confirmation', 'Customer shipping confirmation')], max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], max_length=12)),
                ('recipient', models.EmailField(blank=True, max_length=254)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='commerce.order')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
