# Generated by Django 5.2.17 on 2026-09-22 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_actual_shipping_cost_order_carrier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Private build-cost snapshot captured when the order was placed.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BusinessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incurred_on', models.DateField(db_index=True)),
                ('category', models.CharField(choices=[('payment_fee', 'Payment processing fee'), ('shipping', 'Additional shipping expense'), ('supplies', 'Shop supplies'), ('marketing', 'Marketing'), ('software', 'Software and services'), ('other', 'Other expense')], db_index=True, max_length=20)),
                ('description', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incurred_on', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_business_expense')],
            },
        ),
    ]
