# Generated by Django 5.2.17 on 2026-09-22 16:51

from django.db import migrations, models


def backfill_completed_refunds(apps, schema_editor):
    Refund = apps.get_model('commerce', 'Refund')
    for refund in Refund.objects.filter(status='COMPLETED', completed_at__isnull=True).iterator():
        refund.completed_at = refund.updated_at
        refund.save(update_fields=['completed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_orderitem_unit_cost_businessexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_completed_refunds, migrations.RunPython.noop),
    ]
