from django.urls import path
from . import views

urlpatterns = [
    path('cart/', views.cart_view, name='cart'),
    path('cart/rod/<int:product_id>/', views.cart_change, name='cart_change'),
    path('cart/clear/', views.cart_clear, name='cart_clear'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.my_orders, name='my_orders'),
    path('orders/<uuid:order_id>/', views.order_detail, name='order_detail'),
    path('orders/<uuid:order_id>/receipt/', views.receipt, name='receipt'),
    path('orders/<uuid:order_id>/paypal/', views.start_payment, name='start_payment'),
    path('orders/<uuid:order_id>/confirm/', views.confirm_payment, name='confirm_payment'),
    path('orders/<uuid:order_id>/cancel/', views.cancel, name='cancel_order'),
    path('payments/paypal/webhook/', views.webhook, name='paypal_webhook'),
    path('owner/', views.owner_dashboard, name='owner_dashboard'),
    path('owner/manifest.webmanifest', views.owner_manifest, name='owner_manifest'),
    path('owner/sw.js', views.owner_service_worker, name='owner_service_worker'),
    path('owner/rods/', views.owner_inventory, name='owner_inventory'),
    path('owner/rods/add/', views.owner_rod_add, name='owner_rod_add'),
    path('owner/rods/<int:product_id>/', views.owner_rod_edit, name='owner_rod_edit'),
    path('owner/rods/<int:product_id>/inventory/', views.owner_inventory_update, name='owner_inventory_update'),
    path('owner/tackle/', views.owner_tackle, name='owner_tackle'),
    path('owner/tackle/add/', views.owner_tackle_add, name='owner_tackle_add'),
    path('owner/tackle/<int:product_id>/', views.owner_tackle_edit, name='owner_tackle_edit'),
    path('owner/messages/', views.owner_messages, name='owner_messages'),
    path('owner/messages/<int:message_id>/', views.owner_message, name='owner_message'),
    path('owner/shipping/', views.owner_shipping, name='owner_shipping'),
    path('owner/settings/', views.owner_settings, name='owner_settings'),
    path('owner/reports/', views.owner_reports, name='owner_reports'),
    path('owner/reports/expenses/add/', views.owner_expense_add, name='owner_expense_add'),
    path('owner/reports/export/<str:kind>/', views.owner_report_export, name='owner_report_export'),
    path('owner/orders/<uuid:order_id>/', views.owner_order, name='owner_order'),
    path('owner/orders/<uuid:order_id>/fulfillment/', views.owner_fulfillment, name='owner_fulfillment'),
    path('owner/orders/<uuid:order_id>/receipt/', views.owner_receipt, name='owner_receipt'),
    path('owner/orders/<uuid:order_id>/email/<str:kind>/', views.resend_notification, name='resend_notification'),
]
