# Generated by Django 5.2.17 on 2026-09-22 02:08

import catalog.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBuildRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('fishing_style', models.CharField(blank=True, max_length=120)),
                ('target_species', models.CharField(blank=True, max_length=160)),
                ('fishing_location', models.CharField(blank=True, max_length=160)),
                ('preferred_length', models.CharField(blank=True, max_length=60)),
                ('power_action', models.CharField(blank=True, max_length=120)),
                ('line_weight_preferences', models.CharField(blank=True, max_length=180)),
                ('reel_type', models.CharField(blank=True, max_length=120)),
                ('handle_preferences', models.CharField(blank=True, max_length=160)),
                ('color_preferences', models.CharField(blank=True, max_length=160)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, max_length=4000)),
                ('status', models.CharField(choices=[('received', 'Request received'), ('review', 'Builder review'), ('contacted', 'Customer contacted'), ('confirmed', 'Design confirmed'), ('accepted', 'Build accepted'), ('closed', 'Closed')], default='received', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('rod_id', models.CharField(max_length=60, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('reserved', 'Reserved'), ('made_to_order', 'Made to order'), ('building', 'Building'), ('ready', 'Ready'), ('sold', 'Sold'), ('shipped', 'Shipped'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('build_type', models.CharField(choices=[('stock', 'In stock'), ('unique', 'One of one'), ('made_to_order', 'Made to order'), ('custom', 'Custom order')], default='unique', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('show_in_gallery', models.BooleanField(default=False)),
                ('estimated_build_time', models.CharField(blank=True, max_length=120)),
                ('shipping_estimate', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='positive_product_price'), models.CheckConstraint(condition=models.Q(models.Q(('build_type', 'unique'), _negated=True), ('quantity__lte', 1), _connector='OR'), name='unique_rod_max_one')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.product_image_path, validators=[catalog.models.validate_image_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_text', models.CharField(help_text='Describe the rod or detail shown.', max_length=180)),
                ('position', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RodSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_model', models.CharField(blank=True, max_length=120)),
                ('length', models.CharField(blank=True, max_length=60)),
                ('power', models.CharField(blank=True, max_length=60)),
                ('action', models.CharField(blank=True, max_length=60)),
                ('line_rating', models.CharField(blank=True, max_length=100)),
                ('lure_rating', models.CharField(blank=True, max_length=100)),
                ('blank_manufacturer', models.CharField(blank=True, max_length=100)),
                ('blank_model', models.CharField(blank=True, max_length=100)),
                ('blank_material', models.CharField(blank=True, max_length=100)),
                ('guide_manufacturer', models.CharField(blank=True, max_length=100)),
                ('guide_type', models.CharField(blank=True, max_length=100)),
                ('reel_seat', models.CharField(blank=True, max_length=100)),
                ('handle_material', models.CharField(blank=True, max_length=100)),
                ('handle_style', models.CharField(blank=True, max_length=100)),
                ('grip_configuration', models.CharField(blank=True, max_length=100)),
                ('rear_grip_length', models.CharField(blank=True, max_length=60)),
                ('foregrip_length', models.CharField(blank=True, max_length=60)),
                ('rod_weight', models.CharField(blank=True, max_length=60)),
                ('wrap_colors', models.CharField(blank=True, max_length=160)),
                ('decorative_details', models.TextField(blank=True)),
                ('builder_notes', models.TextField(blank=True)),
                ('primary_fishing_style', models.CharField(blank=True, max_length=100)),
                ('secondary_fishing_style', models.CharField(blank=True, max_length=100)),
                ('plunking_focused', models.BooleanField(default=False)),
                ('salmon_focused', models.BooleanField(default=False)),
                ('bank_shore_use', models.BooleanField(default=False)),
                ('river_use', models.BooleanField(default=False)),
                ('water_type', models.CharField(blank=True, choices=[('freshwater', 'Freshwater'), ('saltwater', 'Saltwater'), ('both', 'Freshwater / saltwater')], max_length=20)),
                ('water_condition_notes', models.TextField(blank=True)),
                ('recommended_line_type', models.CharField(blank=True, max_length=100)),
                ('recommended_line_strength', models.CharField(blank=True, max_length=100)),
                ('recommended_leader_range', models.CharField(blank=True, max_length=100)),
                ('recommended_sinker_range', models.CharField(blank=True, max_length=100)),
                ('recommended_reel_style', models.CharField(blank=True, max_length=100)),
                ('recommended_presentation', models.CharField(blank=True, max_length=160)),
                ('casting_distance_intent', models.CharField(blank=True, max_length=160)),
                ('fighting_power_notes', models.TextField(blank=True)),
                ('builder_usage_notes', models.TextField(blank=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='catalog.product')),
                ('additional_target_species', models.ManyToManyField(blank=True, related_name='additional_rods', to='catalog.species')),
                ('primary_target_species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_rods', to='catalog.species')),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CaCaCa', max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('8.25'), help_text='Percentage, e.g. 8.25. Applied by checkout in the commerce milestone.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('currency', models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3)),
                ('shipping_country', models.CharField(choices=[('US', 'United States')], default='US', max_length=2)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('about_text', models.TextField(blank=True, help_text='Owner-approved builder story.')),
                ('return_policy', models.TextField(blank=True)),
                ('return_policy_published', models.BooleanField(default=False, help_text='Publish only after reviewing the exact terms.')),
            ],
            options={
                'verbose_name': 'store settings',
                'verbose_name_plural': 'store settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='single_store_settings'), models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='valid_tax_percentage')],
            },
        ),
    ]
