# Generated by Django 5.2.17 on 2026-09-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_store_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='design_story',
            field=models.TextField(blank=True, help_text='Describe the hand-wrapped artwork, colors, and details visible in the photos.', verbose_name='Wrap design details'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_theme',
            field=models.ForeignKey(blank=True, help_text='For example: US flag, birds, or another wrap design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rods', to='catalog.designtheme'),
        ),
    ]
