# Generated by Django 5.2.17 on 2026-09-22 03:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_designtheme_product_design_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='checkout_enabled',
            field=models.BooleanField(default=False, help_text='Sandbox checkout only. Requires PostgreSQL, shipping settings, and PayPal sandbox credentials.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='shipping_configured',
            field=models.BooleanField(default=True, help_text='Owner-confirmed default: $15 per order. Zero means free shipping.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='shipping_mode',
            field=models.CharField(choices=[('per_order', 'Per order'), ('per_rod', 'Per rod')], default='per_order', max_length=12),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='shipping_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='tax_shipping',
            field=models.BooleanField(default=False, help_text='Include shipping in the taxable amount when enabled.'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='reserved_stock_within_quantity'),
        ),
    ]
