# Generated by Django 5.2.17 on 2026-09-22 16:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_reserved_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='build_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional private total cost to build this rod. Used for estimated business reporting.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
