# Generated by Django 5.2.17 on 2026-09-22 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombuildrequest',
            name='kind',
            field=models.CharField(choices=[('rod', 'Rod question'), ('question', 'General question'), ('custom', 'Special request')], default='custom', max_length=12),
        ),
        migrations.AddField(
            model_name='custombuildrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_questions', to='catalog.product'),
        ),
    ]
