# Generated by Django 5.2.17 on 2026-09-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_custombuildrequest_kind_custombuildrequest_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_type',
            field=models.CharField(choices=[('rod', 'Fishing rod'), ('tackle', 'Tackle')], db_index=True, default='rod', max_length=12),
        ),
    ]
