# Generated by Django 5.2.17 on 2026-09-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(help_text='Describe the item or detail shown.', max_length=180),
        ),
    ]
