# Generated by Django 5.2.17 on 2026-09-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='shipping_mode',
            field=models.CharField(choices=[('per_order', 'Per order'), ('per_rod', 'Per item')], default='per_order', max_length=12),
        ),
    ]
